/* Regenerates the sprite data module AND a preview sheet from author.mjs.

   The preview is the point. Pixel art cannot be written blind — the first sword
   had a blunt tip, a guard two rows too thick, and grain that read as noise;
   the bow took three passes because it kept reading as a bucket. None of that
   is visible in the source, only in the image.

   Because the data module is emitted from the same run that draws the preview,
   what ships is byte-for-byte what was looked at. There is no transcription
   step to get wrong. */
import fs from 'node:fs';
import path from 'node:path';
import { build, MATERIALS, GEAR_ART, DENSITY } from './author.mjs';
import { encodePNG } from './png.mjs';

const sprites = build();

// ── data module
const q = s => `'${s}'`;
const body = `/* GENERATED by \`npm run sprites\` from tools/sprites/author.mjs — do not edit.
   A test asserts this file matches the authoring source. */

/** Sprite pixels per tile. One pixel size for the whole game. */
export const DENSITY = ${DENSITY};

export const MATERIALS = ${JSON.stringify(MATERIALS, null, 2)
  .replace(/"([A-Z])":/g, '$1:').replace(/"/g, "'")};

export const GEAR_ART = ${JSON.stringify(GEAR_ART, null, 2)
  .replace(/"(\w+)":/g, '$1:').replace(/"/g, "'")};

export const SPRITES = {
${Object.entries(sprites).map(([k, s]) => `  ${k}: {
    material: '${s.material}', tiles: ${s.tiles}, grip: [${s.grip.join(', ')}],
    rows: [
${s.rows.map(r => `      ${q(r)},`).join('\n')}
    ],
  },`).join('\n')}
};
`;
const out = path.resolve('src/render/gear-sprites.js');
fs.writeFileSync(out, body);

// ── preview sheet
const S = 12, GAP = 8;
const list = Object.entries(sprites);
const W = list.reduce((a, [, s]) => a + s.rows[0].length * S + GAP, GAP);
const H = Math.max(...list.map(([, s]) => s.rows.length)) * S + GAP * 2;
const px = new Uint8Array(W * H * 4);
const bg = [20, 27, 34, 255];
for(let i = 0; i < W * H; i++) px.set(bg, i * 4);

const hex = h => [parseInt(h.slice(1,3),16), parseInt(h.slice(3,5),16), parseInt(h.slice(5,7),16), 255];
let ox = GAP;
for(const [, s] of list){
  const pal = MATERIALS[s.material];
  for(let r = 0; r < s.rows.length; r++)
    for(let x = 0; x < s.rows[r].length; x++){
      const c = s.rows[r][x];
      if(c === '.') continue;
      const col = hex(pal[c]);
      for(let dy = 0; dy < S; dy++) for(let dx = 0; dx < S; dx++){
        const X = ox + x*S + dx, Y = GAP + r*S + dy;
        px.set(col, (Y * W + X) * 4);
      }
    }
  ox += s.rows[0].length * S + GAP;
}
fs.mkdirSync('public', { recursive: true });
fs.writeFileSync('public/sprite-sheet.png', encodePNG(W, H, px));

console.log(`${out}`);
for(const [k, s] of list){
  const rear = (s.rows.length - s.grip[1]) * s.tiles / s.rows.length;
  console.log(`  ${k.padEnd(7)} ${s.rows[0].length}x${s.rows.length}  tiles=${s.tiles}  rear=${rear.toFixed(3)}`);
}
console.log('public/sprite-sheet.png');
